#textEng=src/main/resources/english/serov/text5Eng.txt
#textRus=src/main/resources/english/serov/text5Rus.txt
#textEng=src/main/resources/english/serov/text6Eng.txt
#textRus=src/main/resources/english/serov/text6Rus.txt
#textEng=src/main/resources/english/serov/text7Eng.txt
#textRus=src/main/resources/english/serov/text7Rus.txt
#textEng=src/main/resources/english/serov/text8Eng.txt
#textRus=src/main/resources/english/serov/text8Rus.txt
#textEng=src/main/resources/english/tochka/text1Eng.txt
#textRus=src/main/resources/english/tochka/text1Rus.txt
#textEng=src/main/resources/english/tochka/text3Eng.txt
#textRus=src/main/resources/english/tochka/text3Rus.txt
#textEng=src/main/resources/english/tochka/text4Eng.txt
#textRus=src/main/resources/english/tochka/text4Rus.txt
#textEng=src/main/resources/english/tochka/text5Eng.txt
#textRus=src/main/resources/english/tochka/text5Rus.txt
#textEng=src/main/resources/english/tochka/text6Eng.txt
#textRus=src/main/resources/english/tochka/text6Rus.txt
#textEng=src/main/resources/english/tochka/text7Eng.txt
#textRus=src/main/resources/english/tochka/text7Rus.txt
#textEng=src/main/resources/english/tochka/text8Eng.txt
#textRus=src/main/resources/english/tochka/text8Rus.txt
#textEng=src/main/resources/english/tochka/text9Eng.txt
#textRus=src/main/resources/english/tochka/text9Rus.txt
textEng=src/main/resources/english/tochka/text10Eng.txt
textRus=src/main/resources/english/tochka/text10Rus.txt