#textEng=src/main/resources/english/serov/text5Eng.txt
#textRus=src/main/resources/english/serov/text5Rus.txt
#textEng=src/main/resources/english/serov/text6Eng.txt
#textRus=src/main/resources/english/serov/text6Rus.txt
#textEng=src/main/resources/english/serov/text7Eng.txt
#textRus=src/main/resources/english/serov/text7Rus.txt
#textEng=src/main/resources/english/tochka/text1Eng.txt
#textRus=src/main/resources/english/tochka/text1Rus.txt
textEng=src/main/resources/english/tochka/text3Eng.txt
textRus=src/main/resources/english/tochka/text3Rus.txt